version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/pygenesys

    steps:
      - checkout

      - run:
          name: requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .

      - run:
          name: tests
          command: |
            . venv/bin/activate
            py.test

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  main:
    jobs:
      - build-and-test
