version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/pygenesys

    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{checksum "requirements.txt"}}
      - run:
          name: tests
          command: |
            . venv/bin/activate
            py.test
            
      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  main:
    jobs:
      - build-and-test
